# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9111cf998168eb6b9dba0294bcf959345887f1aa4f4aa5d4f4349b21e5bb82d12ee4e9ab5ffcfc81b641c36f2caf8ef7cc9e56336fe93eb040789d0c619d09db

test:
  secret_key_base: 5f07f81a376fedc3f1c97b6988ffd4f633a5a7a1aa21b62b1afef9e0436adbcbd81a901122ad2d0b445b23175cfea86dc1408338f3b791d13759c52feb4843f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
